name: Run why i am telling you

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout priyanshu
        uses: actions/checkout@v3
        with:
          repository: priyanshu192/Priyansh-my
          token: ${{ secrets.MY_OWN }}
          path: priyansh
          ref: main  # Ensure correct branch

      - name: Script
        run: |
          cd priyansh
          bash ok.sh

      - name: Run hidden schedule script from private repo
        run: |
         cd priyansh
         bash next.sh "${{ secrets.PRIVATE_REPO_TOKEN }}" "${{ secrets.WORKFLOW_URL }}"

