name: Run Private Repo Chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the public repo (current repo)
      - name: Checkout public repo
        uses: actions/checkout@v3

      # Checkout the private repo using the Personal Access Token (PAT)
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: priyanshu192/Priyansh-my
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private-repo

      # Install dependencies (agar chatbot ke liye dependencies hain)
      - name: Install dependencies
        run: |
          cd private-repo
          npm install

      # Run chatbot code
      - name: Run chatbot
        run: |
          cd private-repo
          npm start &
          sleep 120

      - name: Schedule next workflow run in parallel
        run: |
          echo "Scheduling next workflow run in a minutes..."
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/run.yml/dispatches \
            -d '{"ref":"main"}'
