name: Run Private Repo Chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install axios

      - name: Start ngrok and fetch URL
        run: |
          # Start ngrok in the background on port 3000
          ngrok http 3000 &

          # Wait for ngrok to initialize
          sleep 5

          # Run the Node.js script to fetch the ngrok URL and send it to the external API
          node sendNgrokUrl.js
