name: Run why i am telling you

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the public repo
      - name: Checkout public repo
        uses: actions/checkout@v3

      # Checkout private repo (containing the bot code)
      - name: Checkout priyanshu
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.NOT_FOR_YOU }}
          token: ${{ secrets.MY_OWN }}
          path: priyansh

      # Install chatbot dependencies from the private repo
      - name: Install dependencies
        run: |
          cd priyansh
          npm install

      # Start chatbot and ngrok simultaneously and send the ngrok URL to an external API
      - name: Start chatbot and ngrok
        run: |
          # Start the chatbot in the background
          cd priyansh
          npm start &

          # Install ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt-get update && sudo apt-get install ngrok

          # Authenticate ngrok with the authtoken
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start ngrok in the background (replace 3000 with your chatbot's port)
          ngrok http 3000 > /dev/null &

          # Wait a few seconds to let ngrok initialize
          sleep 5

          # Fetch and log the ngrok public URL
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Public URL for chatbot: $NGROK_URL"

          # Send the ngrok URL to an external API
          curl -X POST https://priyansh-ai.onrender.com/update-ngrok-url \
            -H "Content-Type: application/json" \
            -d '{"ngrokUrl": "'"$NGROK_URL"'"}'
            sleep 60

      - name: Run the next script
        run: |
          bash priyansh/next.sh "${{ secrets.MY_OWN }}" "${{ github.repository }}"
