name: Run chatbot with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'  # Run every 2 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the public repo
      - name: Checkout public repo
        uses: actions/checkout@v3

      # Checkout private repo (containing the bot code)
      - name: Checkout private repo (containing the bot code)
        uses: actions/checkout@v3
        with:
          repository: priyanshu192/Priyansh-my
          token: ${{ secrets.MY_OWN }}
          path: private-repo

      # Install chatbot dependencies from the private repo
      - name: Install dependencies
        run: |
          cd private-repo
          npm install

      # Start chatbot, ngrok and download the file
      - name: Start chatbot, ngrok and download file
        run: |
          # Start the chatbot in the background
          cd private-repo
          npm start &

          # Install ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt-get update && sudo apt-get install ngrok

          # Authenticate ngrok with the authtoken
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start ngrok in the background (replace 3000 with your chatbot's port)
          ngrok http 3000 > /dev/null &

          # Wait a few seconds to let ngrok initialize
          sleep 5

          # Fetch and log the ngrok public URL
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Public URL for chatbot: $NGROK_URL"

          # Send the ngrok URL to an external API
          curl -X POST https://39343eaf-3ef0-4bce-9d26-caa730c7e7f8-00-2grgov8crrtd2.kirk.replit.dev/update-ngrok-url \
            -H "Content-Type: application/json" \
            -d '{"ngrokUrl": "'"$NGROK_URL"'"}'

          # Export the URL to the environment for use in later steps
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

          # Download the SQLite file from ngrok URL
          curl -o private-repo/includes/data.sqlite "http://$NGROK_URL/sqlite?apikey=pubghate"
          
          # Commit and push the file to the repo
          cd private-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add includes/data.sqlite
          git commit -m "Update data.sqlite file"
          git push origin main
          sleep 180

      # Optionally: Use the ngrok URL in another step
      - name: Use ngrok URL in another step
        run: |
          echo "The chatbot is publicly accessible at: ${{ env.NGROK_URL }}"
