name: Run why i am telling you

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the public repo
      - name: Checkout public repo
        uses: actions/checkout@v3

      # Checkout private repo (containing the bot code)
      - name: Checkout priyanshu
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.NOT_FOR_YOU }}
          token: ${{ secrets.MY_OWN }}
          path: priyansh

            # Set up environment variables
      - name: Set environment variables
        run: |
          echo "NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "EXTERNAL_API_URL=${{ secrets.EXTERNAL_API_URL }}" >> $GITHUB_ENV

      # Make the script executable
      - name: Make start.sh executable
        run: chmod +x priyansh/start.sh

      # Run the start.sh script
      - name: Run start.sh script
        run: priyansh/start.sh

      - name: Run the next script
        run: |
          bash priyansh/next.sh "${{ secrets.MY_OWN }}" "${{ github.repository }}"
